---
title: "Untitled"
output:
  html_document:
    code_folding: hide
    toc: true
    toc_float: true

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



##Scaterplot
```{r scatterplot}
library(tidyverse)


mpg
g <- ggplot(data=mpg, aes(x=displ,y=hwy))+
 geom_point()

```
##Color
```{r color}
g <- ggplot(data=mpg, aes(x=displ,y=hwy, color=class)) +
 geom_point()
g

```
##but need a b&W figure
```{r b&w}
g <- ggplot(data=mpg, aes(x=displ,y=hwy, shape=class))+
 geom_point()
g

```
##Size
```{r size}
g <- ggplot(data=mpg, aes(x=displ,y=hwy, size=class,color=fl))+
 geom_point(alpha=0.4)
g
```
##Exercice
```{r ex}
g <- ggplot(data=mpg)+
 geom_point(aes(x=displ,y=hwy, color=displ<5))
g
```
##multiple geoms
```{r mult_geom}
g <- ggplot(data=mpg)+
 geom_point(aes(x=displ,y=hwy))+
 geom_smooth(aes(x=displ,y=hwy))
g

g <- ggplot(data=mpg, aes(x=displ,y=hwy))+
 geom_point()+
 geom_smooth()
g


```
##customization
```{r customization}

g <- ggplot(data=mpg, aes(x=displ,y=hwy))+
 geom_point()+
 geom_smooth()+
 labs(title="Relationships b/w engine size", x="Highway", y="Engine displacement")+
  theme_bw()
g

```
## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}
plot(pressure)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.

##Data Wrangling with 'dplyr'
```{r dplyr}


gapminder <- readr::read_csv("https://raw.githubusercontent.com/OHI-Science/data-science-training/master/data/gapminder.csv")

###usel functions
head(gapminder)
tail(gapminder)
head(gapminder, 30)
str(gapminder)
names(gapminder)

c(nrow(gapminder),ncol(gapminder))



head(gapminder$country)

filter(gapminder,lifeExp<29)
filter(gapminder,country=="Mexico")

sweden<-filter(gapminder,country=="Sweden")
x <- mean(sweden$lifeExp)
mean(filter(gapminder,country=="Sweden")$lifeExp)

###    '%>%'

gapminder %>% head(3)
head(gapminder,3)

y <- gapminder %>% 
  filter(country=="Sweden") %>% 
  summarize(mean_lifeExp=mean(lifeExp))




```
